// <auto-generated />
using FellingAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FellingAPI.Migrations
{
    [DbContext(typeof(SentimentoDB))]
    [Migration("20230110021854_MudancaKeyword")]
    partial class MudancaKeyword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FellingAPI.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("grafia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("FellingAPI.Entities.Sentimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sentimentos");
                });

            modelBuilder.Entity("KeywordSentimento", b =>
                {
                    b.Property<int>("keywordsId")
                        .HasColumnType("int");

                    b.Property<int>("sentimentosId")
                        .HasColumnType("int");

                    b.HasKey("keywordsId", "sentimentosId");

                    b.HasIndex("sentimentosId");

                    b.ToTable("KeywordSentimento");
                });

            modelBuilder.Entity("KeywordSentimento", b =>
                {
                    b.HasOne("FellingAPI.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("keywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FellingAPI.Entities.Sentimento", null)
                        .WithMany()
                        .HasForeignKey("sentimentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
