// <auto-generated />
using System;
using FellingAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FellingAPI.Migrations
{
    [DbContext(typeof(SentimentoDB))]
    [Migration("20230110012528_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FellingAPI.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SentimentoId")
                        .HasColumnType("int");

                    b.Property<string>("grafia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SentimentoId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("FellingAPI.Entities.Sentimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sentimentos");
                });

            modelBuilder.Entity("FellingAPI.Entities.Keyword", b =>
                {
                    b.HasOne("FellingAPI.Entities.Sentimento", null)
                        .WithMany("keywords")
                        .HasForeignKey("SentimentoId");
                });

            modelBuilder.Entity("FellingAPI.Entities.Sentimento", b =>
                {
                    b.Navigation("keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
